CREATE TABLE emails (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT,
    email_from VARCHAR(255),
    email_to VARCHAR(255),
    subject VARCHAR(255),
    body TEXT,
    sent_date TIMESTAMP,
    status VARCHAR(255),
    CONSTRAINT pk_emails PRIMARY KEY (id)
);